---
title: ivonneg
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ivonnegarcia380@gmail.com
description: User Experience Designer
author: ivonng
baseurl: "/ig"
url: https://ivonneg.github.io/
root: "/octo-5"
twitter_username: chief_toad
github_username: ivonneg
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
